# This values file is used to test the init container functionality
# It shows using an initContainer and a volume to run custom code to provide a model pack
env:
  APP_MEDCAT_MODEL_PACK: "/my/models/custom-model.zip"
volumeMounts:
  - name: model-volume
    mountPath: /my/models
volumes:
  - name: model-volume
    persistentVolumeClaim:
      claimName: medcat-model-pvc

extraInitContainers:
  - name: custom-init-container
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    # For demo purposes - copy the exmple model pack and reference under new path.
    # This demonstrates that we can run any custom code desired to get a model pack.
    command:
      [
        "sh",
        "-c",
        "cp /cat/models/examples/example-medcat-v2-model-pack.zip /my/models/custom-model.zip",
      ]
    volumeMounts:
      - name: model-volume
        mountPath: /my/models

extraManifests:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: medcat-model-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
