# Configuration for the Cogstack Dev Environment
global:
  scrape_interval: 10s # Set the scrape interval to every 10 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 10 seconds. The default is every 1 minute.
scrape_config_files:
  - scrape-configs/*.yml
  - /etc/prometheus/cogstack/site/scrape-targets/*.yml
rule_files:
  - recording-rules/*.yml
  - /etc/prometheus/cogstack/site/recording-rules/*.yml
