# Scrape configs for running local NiFi Stack
scrape_configs:
  - job_name: elasticsearch-exporter # Scrape configuration to get metrics from elasticsearch, eg index size.
    static_configs:
      - targets:
          - cogstack-observability-elasticsearch-exporter:9114
        labels:
          cluster: elasticsearch-cogstack-cluster
  - job_name: "probe-local-stack" # Scrape configuration for using prometheus to probe locally hosted apps, eg for development.
    metrics_path: /probe
    params:
      module: [http_get_200]
    static_configs:
      - targets:
          - https://cogstack-nifi-nginx:8443/nifi-api/access
          - https://cogstack-nifi:8443/nifi-api/access
        labels:
          name: cogstack-nifi
      - targets:
          - cogstack-medcat-trainer-nginx:8000/admin/login
          - cogstack-medcat-trainer-ui:8000/admin/login
        labels:
          name: cogstack-medcat-trainer-ui
      - targets:
          - cogstack-medcat-service-production:5000/api/info
        labels:
          name: cogstack-medcat-service

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: cogstack-observability-blackbox-exporter-1:9115 # The blackbox exporter's real hostname:port.

  - job_name: "blackbox-elastic"
    metrics_path: /probe
    params:
      module: [http_elastic_get_200]
    static_configs:
      - targets:
          - https://elasticsearch-1:9200/_cat/health
        labels:
          name: elasticsearch-1
      - targets:
          - https://elasticsearch-2:9200/_cat/health
        labels:
          name: elasticsearch-2
      - targets:
          - https://cogstack-kibana:5601/app/kibana
        labels:
          name: kibana
    relabel_configs:
      - target_label: env
        replacement: local
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: cogstack-observability-blackbox-exporter-1:9115 # The blackbox exporter's real hostname:port.
