# Scrape metrics from any targets that are exposing Prometheus formatted data. Default is to call the /metrics API. 
# - targets:
#     - cogstack-observability-node-exporter-1:9100
#   labels:
#     job: node_exporter
#     host: localhost