{
 "title": "Cogstack Monitoring Dashboard",
 "description": "This dashboard shows probing of our demo apps and internal endpoints\n\nWith the percentage uptime charts at the top, and the time filter, we can easily say “Over the last 8 hours, we have 99.5% availability”\n\nThe charts of 5m and 8h availability, answer the question of how that change over time “Yesterday, I had a drop in availability over a 5 minute period”\n",
 "tags": [
  "cogstack",
  "apps",
  "availability",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(probe_success{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service Uptime - $job",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "job",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (name) (avg_over_time(probe_success{job=~\"$job\", instance=~\"$instance\"}[$__range])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\"}[30m]"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Uptime (5m)",
   "type": "timeseries",
   "description": "In the last 5 minutes, what percentage of prober calls have been successful ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$instance\", job=~\"$job\"}[5m]) * 100",
     "legendFormat": "{{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Uptime (6h)",
   "type": "timeseries",
   "description": "In the last 5 minutes, what percentage of prober calls have been successful ",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$instance\", job=~\"$job\"}[6h]) * 100",
     "legendFormat": "{{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Burn Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "instance:probe_burnrate:5m{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "instance:probe_burnrate:30m{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "instance:probe_burnrate:1h{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "instance:probe_burnrate:6h{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} {{name}}"
    },
    {
     "expr": "instance:probe_burnrate:3d{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}} {{name}}"
    }
   ]
  },
  {
   "title": "Availability (30d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "instance:probe_success:avg_over_time_30d{job=~\"$job\", instance=~\"$instance\"} * 100\r\n",
     "legendFormat": "{{name}} {{instance}}"
    },
    {
     "expr": "slo_target_over_30_days{job=\"$job\"}  * 100",
     "legendFormat": "30 day SLO Target {{job}}"
    }
   ]
  },
  {
   "title": "Raw Probe Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{name}} {{ phase }}"
    }
   ]
  }
 ]
}