{
 "title": "Docker Metrics in CogStack",
 "description": "Metrics of Docker containers deployed on each host\n\nThis dashboard shows every container we have running, on the VMs in CREATE that have been setup for this.\n\nThis is created having the \"CAdvisor\" exporter running on each VM, being scraped by prometheus.",
 "tags": [
  "cogstack",
  "docker",
  "infra",
  "metrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},host)"
    }
   },
   {
    "name": "instance",
    "label": "IP Address",
    "query": {
     "query": "label_values({__name__=~\"container.*\", host=~\"$host\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", host=~\"$host\", instance=~\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Containers",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{host=~\"$host\",instance=~\"$instance\",name=~\"$container\",name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{host=~\"$host\",instance=~\"$instance\",name=~\"$container\",name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{host=~\"$host\",instance=~\"$instance\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{host=~\"$host\",instance=~\"$instance\",name=~\"$container\",name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{host=~\"$host\",instance=~\"$instance\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{host=~\"$host\",instance=~\"$instance\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}