apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: api-db-backup
  name: api-db-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
