{{- if (and .Values.provisioning .Values.provisioning.enabled) }}
{{- if not .Values.provisioning.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}-provisioning
data:
  provisioning.yaml: |
{{ tpl (toYaml .Values.provisioning.config) . | indent 4 }}
{{- end }}
{{- end }}