apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}-env
  labels:
    {{- include "medcat-trainer-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: medcat-trainer
data:
  CONCEPT_SEARCH_SERVICE_HOST: {{ include "medcat-trainer-helm.solrHost" . | quote  }}
  CONCEPT_SEARCH_SERVICE_PORT: {{ include "medcat-trainer-helm.solrPort" . | quote  }}
  MEDCAT_CONFIG_FILE: "/home/configs/base.txt"
  DB_BACKUP_DIR: "/home/api/db-backup"
  DB_DIR: "/home/api/db"
  DB_PATH: "/home/api/db/db.sqlite3"
  MCT_VERSION: {{ .Values.image.tag | default .Chart.AppVersion }}
  API_URL: http://localhost:{{ .Values.service.apiPort }}/api/
  REMOTE_MODEL_SERVICE_TYPE: "medcat" # TODO: Remove this for REMOTE_MODEL_SERVICE_TYPE after resolving pr-363 in cogstack-nlp

  {{- if .Values.tracing.otlp.enabled }}
    # Tracing configuration
  MCT_ENABLE_TRACING: {{ .Values.tracing.otlp.enabled | quote }}
  OTEL_TRACES_EXPORTER: otlp
  OTEL_SERVICE_NAME: {{ .Values.tracing.serviceName | quote }}
  {{- if .Values.tracing.otlp.grpc.enabled }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.tracing.otlp.grpc.endpoint | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  {{- else if .Values.tracing.otlp.http.enabled }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.tracing.otlp.http.endpoint | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  {{- end }}
  OTEL_METRICS_EXPORTER: none
  OTEL_LOGS_EXPORTER: none
  OTEL_PYTHON_DJANGO_EXCLUDED_URLS: /api/health/*,/metrics
  OTEL_EXPERIMENTAL_RESOURCE_DETECTORS: {{ .Values.tracing.experimentalResourceDetectors | quote }}
  OTEL_PYTHON_DISABLED_INSTRUMENTATIONS: {{ .Values.tracing.disabledInstrumentations | quote }}
  OTEL_RESOURCE_ATTRIBUTES: {{ include "medcat-trainer-helm.tracingResourceAttributesCsv" . }}
  {{- end }}

  {{- if and .Values.provisioning .Values.provisioning.enabled }}
  LOAD_EXAMPLES: "1"
  PROVISIONING_CONFIG_PATH: "/home/configs/provisioning.yaml"
  {{- end }}
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}