apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}-api-media # This stores the uploaded CDB and Vocab models
  labels:
    {{- include "medcat-trainer-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: medcat-trainer
spec:
  {{- with .Values.persistence.media.storageClassName }}
  storageClassName: {{.}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.persistence.media.size}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}-api-static # This stores the HTML for the website. Disk use was 72MB.
  labels:
    {{- include "medcat-trainer-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: medcat-trainer
spec:
  {{- with .Values.persistence.media.storageClassName }}
  storageClassName: {{.}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.persistence.static.size}}
---
#TODO - only create if type using is sqlite
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}-api-db # SQLiteDB
  labels:
    {{- include "medcat-trainer-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: medcat-trainer
spec:
  {{- with .Values.persistence.media.storageClassName }}
  storageClassName: {{.}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.persistence.sqlite.size}}
---
#TODO - only create if type using is sqlite
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "medcat-trainer-helm.fullname" . }}-api-db-backup # SQLiteDB
  labels:
    {{- include "medcat-trainer-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: medcat-trainer
spec:
  {{- with .Values.persistence.media.storageClassName }}
  storageClassName: {{.}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.persistence.sqlite.backupDbSize}}