#cloud-config
# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
# Install Docker
  - echo "Installing Docker"
  # Add Docker's official GPG key:
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl
  - sudo install -m 0755 -d /etc/apt/keyrings
  - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - sudo chmod a+r /etc/apt/keyrings/docker.asc

  # Add the repository to Apt sources:
  - |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - echo "Completed Installing Docker"

# Run Portainer
  - echo "Running Portainer"
  - docker network create portainer-network 
  - docker pull portainer/agent:latest
  - |
    docker run -d \
      --name portainer_agent \
      -p 9001:9001 \
      -e AGENT_SECRET=${PORTAINER_AGENT_SECRET} \
      --network portainer-network \
      --restart unless-stopped  \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -l 'traefik.enable="true"' \
      -l 'traefik.http.routers.portainer-path-router.rule="PathPrefix(`/portainer-agent`)"' \
      portainer/agent:2.33.0
  - echo "Completed running Portainer"

  - echo "Completed Cloud Init"