# Observability main stack. Prometheus and Grafana. 
# Depends on docker-compose.exporters.yml for the network
name: "cogstack-observability"
services:
  prometheus:
    image: cogstacksystems/cogstack-observability-prometheus:latest
    restart: unless-stopped
    volumes:
      - ./probe-simple.yml:/etc/prometheus/cogstack/site/scrape-configs/probers/probe-simple.yml
      - prometheus-data:/prometheus
    networks:
      - observability
  grafana:
    image: cogstacksystems/cogstack-observability-grafana:latest
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - observability
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true # Allows use of grafana without sign in 
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
  traefik:
    image: cogstacksystems/cogstack-observability-traefik:latest
    networks:
     - observability
    restart: unless-stopped
    ports:
      - "180:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro       # So that Traefik can listen to the Docker events
  blackbox-exporter:
    image: cogstacksystems/cogstack-observability-blackbox-exporter:latest
    restart: unless-stopped
    networks:
      - observability
networks:
  observability:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: