# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: main
chart-dirs:
  - deployment/kubernetes/charts
helm-extra-args: --timeout 600s
chart-repos:
  - opensearch=https://opensearch-project.github.io/helm-charts
