apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "medcat-service.fullname" . }}
  labels:
    {{- include "medcat-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "medcat-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "medcat-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "medcat-service.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          {{- range $key, $value := .Values.envValueFrom }}
          - name: {{ $key | quote }}
            valueFrom:
              {{- tpl (toYaml $value) $ | nindent 10 }}
          {{- end }}
          {{- range $key, $value := .Values.env }}
          - name: "{{ tpl $key $ }}"
            value: "{{ tpl (print $value) $ }}"
          {{- end }}
          {{- if .Values.model.downloadUrl }}
          # Note this overrides any previous env setting if downloading is enabled
          - name: "APP_MEDCAT_MODEL_PACK"
            value: "/models/{{ .Values.model.name}}"
          {{- end}}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.model.downloadUrl .Values.volumeMounts }}
          volumeMounts:
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 2 }}
            {{- end }}
            {{- if .Values.model.downloadUrl }}
            - name: models
              mountPath: /models
            {{- end }}
          {{- end }}
      {{- if .Values.model.downloadUrl }}
      initContainers:
        - name: model-downloader
          image: busybox:1.28
          command: 
            - sh
            - -c
            - |
              echo "Downloading model $MODEL_NAME from $MODEL_PACK_URL"
              mkdir -p /models
              wget -O "/models/$MODEL_NAME" "$MODEL_PACK_URL"
              echo "Download finished"
          env:
          - name: MODEL_PACK_URL
            value: {{ .Values.model.downloadUrl}}
          - name: MODEL_NAME
            value: {{ .Values.model.name}}
          volumeMounts:
            - name: models
              mountPath: /models
      {{- end }}
      
      {{- if or .Values.model.downloadUrl .Values.volumes }}
      volumes:
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 2 }}
        {{- end }}
        {{- if .Values.model.downloadUrl }}
        - name: models
          emptyDir: {}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
