apiVersion: v1
kind: Service
metadata:
  name: {{ include "medcat-service.fullname" . }}
  labels:
    {{- include "medcat-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") ( .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else }}
  selector:
    {{- include "medcat-service.selectorLabels" . | nindent 4 }}
