# Scrape Configs for the local VM and the observability stack
scrape_configs:
  - job_name: observability-metrics 
    static_configs:
      - targets:
          - localhost:9090
        labels:
          name: prometheus # collect prometheus's own metrics of itself
          __metrics_path__: /prometheus/metrics
      - targets:
          - cogstack-observability-grafana-1:3000
        labels:
          name: grafana # collect grafana metrics like dashboard usage
          __metrics_path__: /metrics
      - targets:
          - cogstack-observability-traefik-1:8080  # Collect Traefik metrics like number of success calls
        labels:
          name: traefik 
    relabel_configs:
        - target_label: env
          replacement: observability-stack
        - target_label: host
          replacement: prometheus-host