### Prometheus config for probing apps using blackbox exporter
scrape_configs:
  - job_name: "probe-cogstack-availability"
    metrics_path: /blackbox-exporter/probe
    params:
      module: [http_get_200]
    file_sd_configs:
      - files:
          - /etc/prometheus/cogstack/site/scrape-configs/probers/*.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: cogstack-observability-traefik-1 # The blackbox exporter's real host:port.
