apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: solr
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: solr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: solr
    spec:
      containers:
        - args:
            - -cloud
          env:
            - name: CONCEPT_SEARCH_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: CONCEPT_SEARCH_SERVICE_HOST
                  name: env
            - name: CONCEPT_SEARCH_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: CONCEPT_SEARCH_SERVICE_PORT
                  name: env
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: CSRF_TRUSTED_ORIGINS
                  name: env
            - name: DB_BACKUP_DIR
              valueFrom:
                configMapKeyRef:
                  key: DB_BACKUP_DIR
                  name: env
            - name: DB_DIR
              valueFrom:
                configMapKeyRef:
                  key: DB_DIR
                  name: env
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                  key: DB_PATH
                  name: env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: env
            - name: EMAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_HOST
                  name: env
            - name: EMAIL_PASS
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_PASS
                  name: env
            - name: EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_PORT
                  name: env
            - name: EMAIL_USER
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_USER
                  name: env
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: env
            - name: LOAD_EXAMPLES
              valueFrom:
                configMapKeyRef:
                  key: LOAD_EXAMPLES
                  name: env
            - name: LOAD_NUM_DOC_PAGES
              valueFrom:
                configMapKeyRef:
                  key: LOAD_NUM_DOC_PAGES
                  name: env
            - name: MAX_DATASET_SIZE
              valueFrom:
                configMapKeyRef:
                  key: MAX_DATASET_SIZE
                  name: env
            - name: MAX_MEDCAT_MODELS
              valueFrom:
                configMapKeyRef:
                  key: MAX_MEDCAT_MODELS
                  name: env
            - name: MEDCAT_CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  key: MEDCAT_CONFIG_FILE
                  name: env
            - name: OPENBLAS_NUM_THREADS
              valueFrom:
                configMapKeyRef:
                  key: OPENBLAS_NUM_THREADS
                  name: env
            - name: RESUBMIT_ALL_ON_STARTUP
              valueFrom:
                configMapKeyRef:
                  key: RESUBMIT_ALL_ON_STARTUP
                  name: env
            - name: UNIQUE_DOC_NAMES_IN_DATASETS
              valueFrom:
                configMapKeyRef:
                  key: UNIQUE_DOC_NAMES_IN_DATASETS
                  name: env
          image: solr:8
          name: mct-solr
          ports:
            - containerPort: 8983
              protocol: TCP
          volumeMounts:
            - mountPath: /var/solr
              name: solr-data
      restartPolicy: Always
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data
