# Run Exporters on every VM you want metrics from. Grafana Alloy provides multiple components for this
name: "cogstack-observability-exporters"
services:
  alloy:
    image: cogstacksystems/cogstack-observability-alloy:latest
    ports:
      - "12345:12345"
    volumes:
      - ${BASE_DIR-.}/probers:/etc/alloy/probers
      # CAdvisor
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment:
      - PROMETHEUS_URL=http://cogstack-observability-prometheus-1:9090/prometheus
      - ALLOY_HOSTNAME=${ALLOY_HOSTNAME-localhost} # Used to add a label to metrics
      - ALLOY_IP_ADDRESS=${ALLOY_IP_ADDRESS-localhost} # Used to add a label to metrics
    networks:
      - observability-exporters

networks:
  observability-exporters:
    driver: bridge