{{- if .Values.provisioning.enabled }}
apiVersion: v1
kind: Pod
metadata:
  labels:
    {{- include "cogstack-helm-ce.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    #"helm.sh/hook-delete-policy": before-hook-creation
  name: {{ include "cogstack-helm-ce.fullname" . }}-opensearch-provisioning
spec:
  restartPolicy: OnFailure
  containers:
  - image: curlimages/curl
    name: opensearch-provisioning
    command: ["/bin/sh", "/etc/config/opensearch-provisioning-config/opensearch-provisioning.sh"]
    env:
      - name: OPENSEARCH_URL
        value: {{ include "opensearch.url" . }}
      - name: OPENSEARCH_DASHBOARD_URL
        value: {{ include "opensearch-dashboards.url" . }}
      - name: OPENSEARCH_USERNAME
        value: admin
      - name: OPENSEARCH_PASSWORD
        value: {{ include "opensearch.initialAdminPassword" . }}
      - name: CONFIG_DIR
        value: /etc/config/opensearch-provisioning-config
      - name: PROVISION_OPENSEARCH_DASHBOARDS_ENABLED
        value: "{{ .Values.provisioning.opensearchDashboards.createDashboards }}"
      - name: PROVISION_OPENSEARCH_INDEX_TEMPLATE_ENABLED
        value: "{{ .Values.provisioning.opensearch.createIndexTemplate }}"
      - name: PROVISION_OPENSEARCH_EXAMPLE_DOCUMENTS_ENABLED
        value: "{{ .Values.provisioning.opensearch.createExampleDocuments }}"
    volumeMounts:
    - name: opensearch-provisioning-config
      mountPath: /etc/config/opensearch-provisioning-config
  volumes:
    - name: opensearch-provisioning-config
      configMap:
        name: opensearch-provisioning-config
{{- end }}